# Generated by Django 4.2.29 on 2026-03-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule_extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('unknown', 'Unknown')], max_length=20)),
                ('is_valid', models.BooleanField()),
                ('explanation', models.TextField(blank=True)),
                ('batch_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_results', to='rule_extraction.country')),
                ('failed_rules', models.ManyToManyField(blank=True, related_name='failed_validation_results', to='rule_extraction.tinrule')),
                ('matched_rules', models.ManyToManyField(blank=True, related_name='validation_results', to='rule_extraction.tinrule')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('unknown_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='validation_batches/')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
