# Generated by Django 4.2.29 on 2026-03-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinrule',
            name='regex_pattern',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
