# Generated by Django 4.2.29 on 2026-03-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OECDSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_found', models.IntegerField(default=0)),
                ('downloaded_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'oecd_sync_logs',
                'ordering': ['-start_time'],
            },
        ),
    ]
