# Generated by Django 4.2.29 on 2026-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_oecdsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesourcedocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
